export const projects = [
  {
    img: "https://i.postimg.cc/T1Yc3nM3/Screenshot-137.png",
    title: "Adidas Clone",
    des: "A web application for online shopping of shoes, clothing and accessories.",
    demo: "",
    live: "https://rohit753.github.io/Adidas-Clone/ ",
    gitHub: "https://github.com/rohit753/Adidas-Clone.git",
    technologies: ["JavaScript", "HTML", "CSS"],
  },
  {
    img: "https://i.postimg.cc/P5S13g1P/Screenshot-136.png",
    title: "Myntra Clone",
    des: "A web application developed for online shopping for women, men and kids.",
    demo: "",
    live: "https://cranky-knuth-b30b90.netlify.app",
    gitHub: "https://github.com/Ravindraapps/myntraClone.git",
    technologies: ["HTML, CSS, JS, MongoDB, EJS, NodeJS JSON"],
  },
  // {
  // 	img: 'https://i.ibb.co/KGVmQvF/Screenshot-2022-03-21-221824.png',
  // 	title: 'Weather App',
  // 	des: 'This is a cool weather app made in vanilla (pure) Javascript,In this app, I have fetched openweathermap.org API for current weather report. ',
  // 	demo: '',
  // 	live: 'https://hungry-agnesi-4c225c.netlify.app/',
  // 	gitHub: 'https://github.com/Babaji0007/weatherapp',
  // 	technologies: [ 'HTML', 'CSS', "JavaScript"],
  // },
  // {
  // 	img: 'https://camo.githubusercontent.com/b7f4aa8c34ddf776dd19b78dc3488456470a73e5026f48784e9e753601468802/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c62507030307771454537386c6f68584d372f67697068792e676966',
  // 	title: 'Clone of Fitness Blender',
  // 	des: 'This is a clone of the Fitness Blender website. The clone is complete with a Login page, Sign-in page, Shopping Cart, Wishlist and Calendar Scheduling feature. Following is the link to the clone of the website.',
  // 	demo: '',
  // 	live: 'https://anshusagar.github.io/FitnessBlender/',
  // 	gitHub: 'https://github.com/Anshusagar/FitnessBlender.git',
  // 	technologies: ['HTML', 'CSS', 'javaScript'],
  // },
  // {
  // 	img: 'https://github.com/mandarsatam/Mailchimp-Clone/blob/master/Snips/Screenshot%20(79).png?raw=true',
  // 	title: 'Mailchimp Clone',
  // 	des: 'This is a static clone of a website called Mailchimp. This clone includes landing, pricing, our story, and the resources page.',
  // 	demo: '',
  // 	live: 'https://mandarsatam.github.io/Mailchimp-Clone/',
  // 	gitHub: 'https://github.com/mandarsatam/Mailchimp-Clone',
  // 	technologies: ['HTML', 'CSS', 'javaScript'],
  // },
  // {
  // 	img: 'https://user-images.githubusercontent.com/86410106/143928012-c66d0c3c-1f94-4894-b1f0-2326be4f3087.png',
  // 	title: 'Clone of Target.com ',
  // 	des: 'This is a clone of a US-based e-commerce website for all products built with HTML, CSS, JS. Have features that allow users to sort the product on the basis of price, on the payment page users can apply promo codes',
  // 	demo: '',
  // 	live: 'https://pandeypushpendra3.github.io/target/', // deployed link
  // 	gitHub: 'https://github.com/pandeypushpendra3/target/tree/main',
  // 	technologies: [ 'HTML', 'CSS', 'javaScript'],
  // },
];
